# Gebze Technical University 2021 Spring
## ELM368 Digital Signal Processing Laboratory
### This notebook is created by Kutay Acar from instructions of Dr. Köksal Hocaoğlu for mentioned course above

## Basic operations

In [1]:
1 + 4

5

In [2]:
2 * 3

6

In [3]:
5 - 2

3

In [4]:
5 / 2

2.5

In [5]:
5 // 2

2

In [6]:
3 ** 2

9

In [7]:
10 % 3

1

In [8]:
abs(-5)

5

## Complex Numbers

In [9]:
1 + 2j

(1+2j)

In [10]:
complex(1,2)

(1+2j)

In [11]:
a = 1 + 2j
a.real

1.0

In [12]:
a.imag

2.0

In [13]:
abs(a)

2.23606797749979

In [14]:
z = 1 + 2j
w = 3 - 1j

In [15]:
z + w

(4+1j)

In [16]:
z - w

(-2+3j)

In [17]:
z / w

(0.1+0.7000000000000001j)

In [18]:
z * w

(5+5j)

## Boolean

In [19]:
a = 1
b = 2
a > b

False

In [20]:
a = 1
b = 2
a < b

True

In [21]:
c = 3
d = 3
c == d

True

In [22]:
c = 3 
d = 3
c != d

False

In [23]:
a = 1
b = 2
c = 3 
d = 3
a > b or c <= d

True

In [24]:
a = 1
b = 2 
c = 3 
d = 3
a <= b and c >= d

True

## Lists

In [25]:
a = [ -1, 0, 5, 7 ]
len(a)

4

In [26]:
a = [ -1 , 0, 5, 7]
a[0]

-1

In [27]:
a = [ -1, 0, 5, 7 ]
a[:]

[-1, 0, 5, 7]

In [30]:
a[ 0:3 ]

[-1, 0, 5]

In [31]:
a[ 0:4 ]

[-1, 0, 5, 7]

In [32]:
a = [ -3, 27, 9, 98, 22, 15, 65, 53 ]
a[0:6]

[-3, 27, 9, 98, 22, 15]

In [33]:
a[ 0:6:2 ]

[-3, 9, 22]

In [34]:
a[0:6:3]

[-3, 98]

In [35]:
a[::]

[-3, 27, 9, 98, 22, 15, 65, 53]

In [36]:
a[::2]

[-3, 9, 22, 65]

In [37]:
a[:3]

[-3, 27, 9]

In [38]:
a[3]

98

In [39]:
a = [-1, 0, 5, 7]
a[2:len(a)+1]

[5, 7]

In [40]:
a = [ -1, 0, 5, 7]
a.append(10)
a[:]

[-1, 0, 5, 7, 10]

In [41]:
a = [1, 2, 3]
b = [7, 8, 9]
a.extend(b)
a[:]

[1, 2, 3, 7, 8, 9]

In [42]:
a = [1, 2, 3]
b = [7, 8, 9]
c = a + b 
print(c)

[1, 2, 3, 7, 8, 9]


In [43]:
a = [ 7, 0, 17, 8 ]
a.sort()
a[:]

[0, 7, 8, 17]

In [44]:
a.sort(reverse = True)
a[:]

[17, 8, 7, 0]

In [45]:
a.remove(0)
a[:]

[17, 8, 7]

## Arrays

In [48]:
#!pip install numpy

     |████████████████████████████████| 15.4 MB 1.7 MB/s eta 0:00:01    |█▋                              | 757 kB 702 kB/s eta 0:00:21     |██▌                             | 1.2 MB 702 kB/s eta 0:00:21     |███▌                            | 1.7 MB 702 kB/s eta 0:00:20     |██████                          | 2.9 MB 702 kB/s eta 0:00:18     |███████                         | 3.4 MB 702 kB/s eta 0:00:18     |███████▋                        | 3.7 MB 702 kB/s eta 0:00:17     |██████████                      | 4.8 MB 3.2 MB/s eta 0:00:04     |█████████████▏                  | 6.3 MB 3.2 MB/s eta 0:00:03     |█████████████████▉              | 8.6 MB 5.0 MB/s eta 0:00:02     |██████████████████▎             | 8.8 MB 5.0 MB/s eta 0:00:02     |████████████████████            | 9.6 MB 5.0 MB/s eta 0:00:02     |█████████████████████▎          | 10.2 MB 5.0 MB/s eta 0:00:02     |█████████████████████▋          | 10.4 MB 5.0 MB/s eta 0:00:01     |██████████████████████████▏     | 12.5 MB 2.1 MB/s eta

In [49]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([7, 8, 9])
print("a = ", a )
print( "b = ", b )

c = a + b
print( "c = ", c )

a =  [1 2 3]
b =  [7 8 9]
c =  [ 8 10 12]


In [51]:
import numpy as np

a = np.arange(7)
print(a)

[0 1 2 3 4 5 6]


In [52]:
len(a)

7

In [53]:
a.ndim

1

In [54]:
print(a[0], a[1], a[4])

0 1 4


In [55]:
2**a

array([ 1,  2,  4,  8, 16, 32, 64])

In [56]:
b = np.array([[1,2,3],[7,8,9]])
print(b)

[[1 2 3]
 [7 8 9]]


In [57]:
len(b)

2

In [58]:
b.ndim

2

In [59]:
b.shape

(2, 3)

In [60]:
2**b

array([[  2,   4,   8],
       [128, 256, 512]])

In [61]:
c = np.linspace( 10, 30, 3 )
print(c)

[10. 20. 30.]


In [62]:
d = np.linspace( 10, 30, 6 )
print( d )

[10. 14. 18. 22. 26. 30.]


In [63]:
d = np.linspace( 10, 30, 6, endpoint = False)
print( d )

[10.         13.33333333 16.66666667 20.         23.33333333 26.66666667]


In [64]:
e = np.arange( 10 , 30 ,6 )
print( e )

[10 16 22 28]


In [65]:
a = np.ones( [3,3] )
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [66]:
a = np.zeros([1,5])
print(a)

[[0. 0. 0. 0. 0.]]


In [67]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [68]:
a = np.random.rand(4)
print(a)

[0.61044162 0.72699943 0.03613441 0.14520411]


## Print

In [69]:
print("Hello Python!")

Hello Python!


In [70]:
"Hello" + "Python"

'HelloPython'

In [71]:
"Hello"*3

'HelloHelloHello'

In [72]:
print("I love 'ELM367'")

I love 'ELM367'


In [74]:
print("Hello\nPython!")

Hello
Python!


In [75]:
print("Hello\tPython!")

Hello	Python!


In [76]:
x = 5 
print(x)

5


In [77]:
y = x + 3
print(y)

8


In [78]:
a,b = 2,3
print(a)
print(b)

2
3


In [79]:
z = 3 
z += 2 
print(z)

5


In [80]:
z = 5
z -= 2
print(z)

3


In [81]:
z =3 
z *= 2
print(z)

6


In [82]:
a = 3
b = 2
c = a + b
print(c)

5


In [84]:
u = 4
v = 3
z = u / v
t = u // v
print(z)
print(t)

1.3333333333333333
1


## If - Else

In [85]:
x = 8 
y = 9
if x < y:
    print(" x < y ")
else:
    print(" x >= y ")

 x < y 


In [86]:
points = 8 
if points >= 9:
    prtin("A")
elif points >= 8:
    print("B")
elif points >= 7:
    print("C")
elif points >= 6:
    print("D")
else:
    print("F")

B


In [88]:
if points >= 9:
    print("A")
    print("Z")
    points2 = points * 5
elif points >= 8:
    print("B")
    points2 = points * 4
elif points >= 7:
    print("C")
    points2 = points * 3
elif points >= 6:
    print("D")
    points2 = points * 2
else:
    print("F")
    points2 = points * 0.5
print("points2 = ", points2)

B
points2 =  32


## For